<?php
/**
 * Re-encrypt plaintext .drawio esportati dal VPS con la KMS corrente
 * locale + sostituisce i blob in storage/maps_enc/{teacher_id}/.
 * Aggiorna teacher_content.map_blob_path se cambia il ULID.
 *
 * Pre-requisito: tools/crypto/_export_mappe_<tid>/ con file <id>.drawio +
 * _manifest.json (output di export_mappa_plaintext.php sul VPS).
 *
 * Sicurezza:
 *   - Idempotente: ri-encryption ULID sempre nuovo, vecchio blob non viene
 *     cancellato (rinominato .old.bin per safety).
 *   - Verifica sha256 plaintext vs manifest prima di accettare.
 *
 * Usage: php tools/crypto/reimport_mappa_plaintext.php <teacher_id> [--dry-run]
 */
declare(strict_types=1);
require __DIR__ . '/../../app/bootstrap.php';

$teacherId = (int)($argv[1] ?? 0);
$dryRun    = in_array('--dry-run', $argv, true);
if ($teacherId <= 0) {
    fwrite(STDERR, "Usage: php tools/crypto/reimport_mappa_plaintext.php <teacher_id> [--dry-run]\n");
    exit(1);
}

$srcDir = __DIR__ . '/_export_mappe_' . $teacherId;
if (!is_dir($srcDir)) {
    fwrite(STDERR, "Source dir not found: $srcDir\n");
    fwrite(STDERR, "Run export_mappa_plaintext.php on VPS + transfer here first.\n");
    exit(1);
}

$manifestFile = $srcDir . '/_manifest.json';
if (!is_file($manifestFile)) {
    fwrite(STDERR, "Manifest missing: $manifestFile\n");
    exit(1);
}
$manifest = json_decode((string)file_get_contents($manifestFile), true);
if (!is_array($manifest)) {
    fwrite(STDERR, "Manifest invalid JSON.\n");
    exit(1);
}

$db = App\Core\Database::connection();
$store = new App\Services\Maps\MapBlobStore();

$ok = 0; $fail = 0; $skipped = 0;
foreach ($manifest as $entry) {
    $id    = (int)$entry['id'];
    $title = (string)$entry['title'];
    $file  = $srcDir . '/' . $id . '.drawio';

    if (!is_file($file)) {
        echo "SKIP id=$id ($title): plaintext file missing\n"; $skipped++; continue;
    }
    $plain = (string)file_get_contents($file);
    $sha = hash('sha256', $plain);
    if ($sha !== ($entry['sha256'] ?? '')) {
        echo "FAIL id=$id ($title): sha256 mismatch (file corrupted?)\n"; $fail++; continue;
    }

    if ($dryRun) {
        echo "DRY id=$id ($title): " . strlen($plain) . " bytes ready for re-encrypt\n"; $ok++; continue;
    }

    try {
        // Re-encrypt + write new blob (new ULID auto-generated by MapBlobStore::put).
        $newRelPath = $store->put($teacherId, $plain);

        // Rename old blob to .old.bin (safety, rollback se serve).
        $oldRelPath = (string)$entry['blob_path'];
        $oldAbs = __DIR__ . '/../../storage/maps_enc/' . $oldRelPath;
        if (is_file($oldAbs) && $oldRelPath !== $newRelPath) {
            @rename($oldAbs, $oldAbs . '.old.bin');
        }

        // Update DB row.
        $upd = $db->prepare('UPDATE teacher_content SET map_blob_path = ? WHERE id = ?');
        $upd->execute([$newRelPath, $id]);

        echo "OK  id=$id ($title): new blob $newRelPath\n";
        $ok++;
    } catch (Throwable $e) {
        echo "FAIL id=$id ($title): " . $e->getMessage() . "\n";
        $fail++;
    }
}

echo "\nDone: $ok ok, $fail fail, $skipped skipped.";
echo $dryRun ? " (DRY RUN — no changes written)\n" : "\n";
echo "Old blobs renamed to .old.bin (manual cleanup later if all green).\n";
