name: Deploy Production

# Si attiva quando fai push sul branch master
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        
    - name: Deploy to Production Server via FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /www.pantedu.eu/  # Root del sito live
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.vscode/**
          **/log/data/*.json
          **/temp/**
          **/.github/**
